const Products=[
    {
    id: 1,
    name: " Winter Coat",
    price: 50.00,
    description:"Winter coat for women with insulating materials like down, fleece, and wool for warmth. Adjustable cuffs and hem for a custamizable fit.",
    imgURL:require("./img/unsplash_Zq4dVEMAZXo.png"),
    ratings:require("./img/star1.png"),
    },
    {
    id: 2,
    name: "Acrylic Sweater",
    price: 39.9,
    description:"Acrylic sweater made from acrylic fibers, synthetic materials. Known for It’s warmth, softness and durability.",
    imgURL:require ("./img/unsplash_8Lsy75LqGVc.png"),
    ratings:require("./img/star1.png"),
    },
    {
    id: 3,
    name: "Acrylic Sweater",
    price: 39.9,
    description:"Zip-Up Cardigan with a stand-up collar and a zip. Versatile, easy to wear, adjustable, comfortable and sporty.",
    imgURL:require ("./img/unsplash_kpvIazqLOoA.png"),
    ratings:require("./img/star3.png"),
    },
    {
    id: 4,
    name: "V-Neck Cardigan",
    price: 39.9,
    description:"V-Neck cardigan suitable for formal or casual occasions. Versatile and easy to pair with dresses, shirts, or sweaters.",
    imgURL:require ("./img/unsplash_Zq4dVEMAZXo.png"),
    ratings:require("./img/star1.png"),
    },
    {
    id: 5,
    name: "Kids Cardigan ",
    price: 39.9,
    description:"Kids cardigan suitable for formal or casual occasions. Versatile and easy to pair with dresses, shirts, or sweaters.",
    imgURL:require ("./img/unsplash_LorcFaKYk34.png"),
    ratings:require("./img/star2.png"),
    },
    {
    id: 6,
    name: "Quilted Jacket",
    price: 39.9,
    description:"Quilted Jacket is made from multiple layers of fabric stitched together to create a thick, padded, and warm material.",
    imgURL:require ("./img/elegantsuit.png"),
    ratings:require("./img/star1.png"),
    },
    {
    id: 7,
    name: "Acrylic sweater",
    price: 39.9,
    description:"Acrylic sweater made from acrylic fibers, synthetic materials. Known for It’s warmth, softness and durability.",
    imgURL:require ("./img/pinkwarm.png"),
    ratings:require("./img/star1.png"),
    },
    {
    id: 8,
    name: "Acrylic sweater",
    price: 39.9,
    description:"Acrylic sweater made from acrylic fibers, synthetic materials. Known for It’s warmth, softness and durability.",
    imgURL:require ("./img/bigbutton.png"),
    ratings:require("./img/star2.png"),
    },
    {
    id: 9,
    name: "Heavy knit cardigan",
    price: 39.9,
    description:"Heavy knit cardigan made from thick, robust yarns. It provides extra warmth and comfort.",
    imgURL:require ("./img/menshawl.png"),
    ratings:require("./img/star1.png"),
    },
    {
    id: 10,
    name: "Kids Cardigan",
    price: 39.9,
    description:"Kids cardigan suitable for formal or casual occasions. Versatile and easy to pair with dresses, shirts, or sweaters.",
    imgURL:require ("./img/kidscardigan.png"),
    ratings:require("./img/star2.png"),
    },
]

export default Products;